name: Ci branch

on: push

env:
  NX_BASE: ${{  github.event.pull_request.head.sha || format('{0}{1}', github.ref_name, '~1')}}
  NX_HEAD:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn install
      - run: npm install -g nx
      - name: Lint mono
        run: nx affected lint --head ${{ github.sha }} --base 'origin/master'
      - name: Test mono
        run: nx affected test --head ${{ github.sha }} --base 'origin/master'
      - name: Build mono
        run: nx affected build --head ${{ github.sha }} --base 'origin/master'
      - name: Deploy mono
        if: ${{ github.ref == 'refs/heads/master' }}
        run: nx affected deploy --head ${{ github.sha }} --base 'origin/master'
